// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8x7ZEwpsfUdiRouwBjZP82L7fpfcKbdk',
    appId: '1:1080355417671:web:6ebb14aa7c266249844b62',
    messagingSenderId: '1080355417671',
    projectId: 'aanacrops-riceking',
    authDomain: 'aanacrops-riceking.firebaseapp.com',
    storageBucket: 'aanacrops-riceking.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhfZ3z3rmRi71DP0NZ07v4GmWBT4uAZJM',
    appId: '1:1080355417671:android:22b48d5f82e6ca25844b62',
    messagingSenderId: '1080355417671',
    projectId: 'aanacrops-riceking',
    storageBucket: 'aanacrops-riceking.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBjcT3tXIseHJQyY9yF-Re_ILjHuH6iLQ',
    appId: '1:1080355417671:ios:edbb4ec0818f1a69844b62',
    messagingSenderId: '1080355417671',
    projectId: 'aanacrops-riceking',
    storageBucket: 'aanacrops-riceking.firebasestorage.app',
    iosBundleId: 'com.aanacrops.riceking',
  );
}
